/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.table.DefaultTableModel;
import simulacia.KozmetickySalon;

/**
 *
 * @author Jožko
 */
public class ReplikacieOkno extends javax.swing.JFrame {

    /**
     * Creates new form ReplikacieOkno
     */
    public ReplikacieOkno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pocetRec = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pocetKad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pocetKoz = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pocetRep = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabulkaVysledkov = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Rec:");

        jLabel2.setText("Kad:");

        jLabel3.setText("Koz:");

        jLabel4.setText("Rep:");

        tabulkaVysledkov.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Vyťaženie recepčných [%]", "0", "0"},
                {"Vyťaženie kaderníčok [%]", "0", "0"},
                {"Vyťaženie kozmetíčok [%]", "0", "0"},
                {"Čas v systéme", "0", "0"},
                {"Čas v rade - recepčné objednávka", "0", "0"},
                {"Čas v rade - recepčné platba", "0", "0"},
                {"Čas v rade - kaderníčky", "0", "0"},
                {"Čas v rade - kozmetičky čistenie", "0", "0"},
                {"Čas v rade - kozmetičky líčenie", "0", "0"},
                {"Dĺžka radu - recepčné objednávka", "0", "0"},
                {"Dĺžka radu - recepčné platba", "0", "0"},
                {"Dĺžka radu - kaderníčky", "0", "0"},
                {"Dĺžka radu - kozmetičky", "0", "0"},
                {"Čas obsluhy - recepčné", "0", "0"},
                {"Čas obsluhy - kaderníčky", "0", "0"},
                {"Čas obsluhy - kozmetičky", "0", "0"},
                {"Otvorené naviac", "0", null},
                {"Počet vyhodených z radu recepčné", "0", null}
            },
            new String [] {
                "Štatistika", "Hodnota", "Hodnota bez"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabulkaVysledkov);

        jButton1.setText("Štart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pocetRec, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pocetKad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pocetKoz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pocetRep, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pocetRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(pocetKad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(pocetKoz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(pocetRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        KozmetickySalon salon;
        salon = new KozmetickySalon(28800, Integer.parseInt(pocetRec.getText()), Integer.parseInt(pocetKad.getText()), Integer.parseInt(pocetKoz.getText()), Integer.parseInt(pocetRep.getText()));                     
        salon.zmenaMedzerySpojitostSimulacie(100000);
        salon.vykonajVsetkyReplikacie();
        
        DefaultTableModel modelVysl = (DefaultTableModel) tabulkaVysledkov.getModel();
        
        // aktualizacia tabulky priemernymi vyslednymi hodnotami z replikacii
        modelVysl.setValueAt(String.format("%.2f", salon.dajPriemerneVytazenieRecepcnychPoReplikaciach()), 0, 1);
        modelVysl.setValueAt(String.format("%.2f", salon.dajPriemerneVytazenieKadernicokPoReplikaciach()), 1, 1);
        modelVysl.setValueAt(String.format("%.2f", salon.dajPriemerneVytazenieKozmeticokPoReplikaciach()), 2, 1);
        modelVysl.setValueAt("< " + salon.dajFormatovanySimulacnyCas(salon.dajLavostrannyInterval90CasuZakaznikaVSysteme()) + " ; " + salon.dajFormatovanySimulacnyCas(salon.dajPriemernyCasZakaznikaVSystemePoReplikaciach()) + " ; " + salon.dajFormatovanySimulacnyCas(salon.dajPravostrannyInterval90CasuZakaznikaVSysteme()) + " >", 3, 1);
        modelVysl.setValueAt(salon.dajFormatovanySimulacnyCas(salon.dajPriemernyCasVRadePredRecepcnymiObjednavkaPoReplikaciach()), 4, 1);
        modelVysl.setValueAt(salon.dajFormatovanySimulacnyCas(salon.dajPriemernyCasVRadePredRecepcnymiPlatbaPoReplikaciach()), 5, 1);
        modelVysl.setValueAt(salon.dajFormatovanySimulacnyCas(salon.dajPriemernyCasVRadePredKadernickamiPoReplikaciach()), 6, 1);
        modelVysl.setValueAt(salon.dajFormatovanySimulacnyCas(salon.dajPriemernyCasVRadePredKozmetickamiCisteniePoReplikaciach()), 7, 1);
        modelVysl.setValueAt(salon.dajFormatovanySimulacnyCas(salon.dajPriemernyCasVRadePredKozmetickamiLiceniePoReplikaciach()), 8, 1);
        modelVysl.setValueAt(String.format("%.2f", salon.dajPriemernuDlzkuRaduPredRecepcnymiObjednavkaPoReplikaciach()), 9, 1);
        modelVysl.setValueAt(String.format("%.2f", salon.dajPriemernuDlzkuRaduPredRecepcnymiPlatbaPoReplikaciach()), 10, 1);
        modelVysl.setValueAt(String.format("%.2f", salon.dajPriemernuDlzkuRaduPredKadernickamiPoReplikaciach()), 11, 1);
        modelVysl.setValueAt(String.format("%.2f", salon.dajPriemernuDlzkuRaduPredKozmetickamiPoReplikaciach()), 12, 1);
        modelVysl.setValueAt(salon.dajFormatovanySimulacnyCas(salon.dajPriemernuDobuObsluhyRecepcnymiPoReplikaciach()), 13, 1);
        modelVysl.setValueAt(salon.dajFormatovanySimulacnyCas(salon.dajPriemernuDobuObsluhyKadernickamiPoReplikaciach()), 14, 1);
        modelVysl.setValueAt(salon.dajFormatovanySimulacnyCas(salon.dajPriemernuDobuObsluhyKozmetickamiPoReplikaciach()), 15, 1);
        modelVysl.setValueAt(salon.dajFormatovanySimulacnyCas(salon.dajPriemernuDobuPracovaniaNaviacPoReplikaciach()), 16, 1);
        modelVysl.setValueAt(String.format("%.2f", salon.dajPriemernyPocetVyhodenychLudiPoReplikaciachBO()), 17, 1);
        
        // aktualizacia tabulky priemernymi vyslednymi hodnotami z replikacii - statistiky do 17:00
        modelVysl.setValueAt(String.format("%.2f", salon.dajPriemerneVytazenieRecepcnychPoReplikaciachBO()), 0, 2);
        modelVysl.setValueAt(String.format("%.2f", salon.dajPriemerneVytazenieKadernicokPoReplikaciachBO()), 1, 2);
        modelVysl.setValueAt(String.format("%.2f", salon.dajPriemerneVytazenieKozmeticokPoReplikaciachBO()), 2, 2);
        modelVysl.setValueAt("< " + salon.dajFormatovanySimulacnyCas(salon.dajLavostrannyInterval90CasuZakaznikaVSystemeBO()) + " ; " + salon.dajFormatovanySimulacnyCas(salon.dajPriemernyCasZakaznikaVSystemePoReplikaciachBO()) + " ; " + salon.dajFormatovanySimulacnyCas(salon.dajPravostrannyInterval90CasuZakaznikaVSystemeBO()) + " >", 3, 2);
        modelVysl.setValueAt(salon.dajFormatovanySimulacnyCas(salon.dajPriemernyCasVRadePredRecepcnymiObjednavkaPoReplikaciachBO()), 4, 2);
        modelVysl.setValueAt(salon.dajFormatovanySimulacnyCas(salon.dajPriemernyCasVRadePredRecepcnymiPlatbaPoReplikaciachBO()), 5, 2);
        modelVysl.setValueAt(salon.dajFormatovanySimulacnyCas(salon.dajPriemernyCasVRadePredKadernickamiPoReplikaciachBO()), 6, 2);
        modelVysl.setValueAt(salon.dajFormatovanySimulacnyCas(salon.dajPriemernyCasVRadePredKozmetickamiCisteniePoReplikaciachBO()), 7, 2);
        modelVysl.setValueAt(salon.dajFormatovanySimulacnyCas(salon.dajPriemernyCasVRadePredKozmetickamiLiceniePoReplikaciachBO()), 8, 2);
        modelVysl.setValueAt(String.format("%.2f", salon.dajPriemernuDlzkuRaduPredRecepcnymiObjednavkaPoReplikaciachBO()), 9, 2);
        modelVysl.setValueAt(String.format("%.2f", salon.dajPriemernuDlzkuRaduPredRecepcnymiPlatbaPoReplikaciachBO()), 10, 2);
        modelVysl.setValueAt(String.format("%.2f", salon.dajPriemernuDlzkuRaduPredKadernickamiPoReplikaciachBO()), 11, 2);
        modelVysl.setValueAt(String.format("%.2f", salon.dajPriemernuDlzkuRaduPredKozmetickamiPoReplikaciachBO()), 12, 2);
        modelVysl.setValueAt(salon.dajFormatovanySimulacnyCas(salon.dajPriemernuDobuObsluhyRecepcnymiPoReplikaciachBO()), 13, 2);
        modelVysl.setValueAt(salon.dajFormatovanySimulacnyCas(salon.dajPriemernuDobuObsluhyKadernickamiPoReplikaciachBO()), 14, 2);
        modelVysl.setValueAt(salon.dajFormatovanySimulacnyCas(salon.dajPriemernuDobuObsluhyKozmetickamiPoReplikaciachBO()), 15, 2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Menu().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReplikacieOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReplikacieOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReplikacieOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReplikacieOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReplikacieOkno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pocetKad;
    private javax.swing.JTextField pocetKoz;
    private javax.swing.JTextField pocetRec;
    private javax.swing.JTextField pocetRep;
    private javax.swing.JTable tabulkaVysledkov;
    // End of variables declaration//GEN-END:variables
}
